# Generated by Django 3.1.7 on 2021-03-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_remove_client_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realties', to='realty.client'),
        ),
    ]
